### ISSUE TITLE
anyenvインストールスクリプトを設定

### ISSUE THREAD

**Issue by watame** [watame/setup_for_mac#12]
# やること
anyenvを利用可能な設定を組み込む
- 参考URL
  - https://qiita.com/rinpa/items/81766cd6a7b23dea9f3c

# TODO
- [x] 変数に `anyenv` を追加する
- [x] shellへの環境変数読み込み処理を追加する
- [x] `anyenv install --init` をスクリプトに組み込む
- [x] 設定を定義した `.zshrc` を用いて利用が可能かを確認する

**Comment by watame** [comment]
変数へパッケージを追加し、正常にインストールされることを確認した。
![Image](https://user-images.githubusercontent.com/16306537/183295128-9f7bd45d-624b-4ec7-b470-1dcd2e26500a.png)

**Comment by watame** [comment]
- 環境変数読み込み処理の追加
  - https://github.com/watame/dotfiles/commit/275cc2c0ea7c2833bf475919ebea93809b7873b3
- スクリプトの組み込み
  - https://github.com/watame/setup_for_mac/commit/f7deb54c50b6280b4e620e2639a30f28f84a158c

**Comment by watame** [comment]
.zshrcを反映した
- https://github.com/watame/setup_for_mac/commit/f627835d5a0ee792242784982fdacbb4ab85dc8d
