### ISSUE TITLE
oh my zshインストールスクリプトを設定

### ISSUE THREAD

**Issue by watame** [watame/setup_for_mac#13]
# やること
oh my zsh をインストールし、適切な設定がされるdotfileを適用する

# TODO
- [x] shellを変更するスクリプトを追加
  - [x] 
- [x] スクリプトに下記拡張の設定を追加
  - [ ] (Option) https://github.com/romkatv/powerlevel10k
  - [x] https://github.com/zsh-users/zsh-autosuggestions
  - [x] https://github.com/zsh-users/zsh-syntax-highlighting
- [x] dotfileに下記の拡張の設定を追加
  - [ ] (Option) https://github.com/romkatv/powerlevel10k
  - [x] https://github.com/zsh-users/zsh-autosuggestions
  - [x] https://github.com/zsh-users/zsh-syntax-highlighting

**Comment by watame** [comment]
スクリプトの設定が行われることは確認済み。
また、初期値となる `.zshrc` も `dotfiles` レポジトリに追加済み。
https://github.com/watame/dotfiles/tree/ea43629cb33dd0910df9056ba8b4f36b81d6d24d

**Comment by watame** [comment]
- スクリプトへの拡張追加
  - https://github.com/watame/setup_for_mac/commit/9a0d288019574abd93db73fe7536d5f4935d7919
- dotfileへの拡張設定追加
  - https://github.com/watame/dotfiles/commit/a44ac3370269015567a3feda03b9e0b39b4f187e

**Comment by watame** [comment]
dotfilesのタスクを削除する必要はないので、削除タスクは行わない

**Comment by watame** [comment]
下記コミットにより本Issueは終了
- .zshrcの反映
  - https://github.com/watame/setup_for_mac/commit/f627835d5a0ee792242784982fdacbb4ab85dc8d
- oh my zshインストール後に .zshrc をリストア
  - https://github.com/watame/setup_for_mac/commit/3d947663897bddbcb26e08992a0572c1f59968a1
